-- MySQL Script generated by MySQL Workbench
-- Mon May 25 16:53:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce_deportivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce_deportivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce_deportivo` DEFAULT CHARACTER SET utf8mb4 ;
USE `ecommerce_deportivo` ;

-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `rol` ENUM('admin', 'cliente') NULL DEFAULT 'cliente',
  `estado` TINYINT(1) NULL DEFAULT 1,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`carrito` (
  `id_carrito` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_carrito`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `carrito_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecommerce_deportivo`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`categorias` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`productos` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `marca` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT 1,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `genero` ENUM('hombre', 'mujer', 'unisex') NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `FK_PRODUCTO_CATEGORIA` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `FK_PRODUCTO_CATEGORIA`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `ecommerce_deportivo`.`categorias` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`producto_caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`producto_caracteristicas` (
  `id_caract` INT(11) NOT NULL AUTO_INCREMENT,
  `id_producto` INT(11) NOT NULL,
  `talla` VARCHAR(20) NOT NULL,
  `color` VARCHAR(50) NOT NULL,
  `stock` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`id_caract`),
  INDEX `FK_CARACTERISTICA_PRODUCTO` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `FK_CARACTERISTICA_PRODUCTO`
    FOREIGN KEY (`id_producto`)
    REFERENCES `ecommerce_deportivo`.`productos` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`carrito_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`carrito_detalle` (
  `id_detalle` INT(11) NOT NULL AUTO_INCREMENT,
  `id_carrito` INT(11) NOT NULL,
  `id_caract` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `FK_DETALLE_CARRITO` (`id_carrito` ASC) VISIBLE,
  INDEX `FK_V` (`id_caract` ASC) VISIBLE,
  CONSTRAINT `FK_DETALLE_CARRITO`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `ecommerce_deportivo`.`carrito` (`id_carrito`),
  CONSTRAINT `FK_V`
    FOREIGN KEY (`id_caract`)
    REFERENCES `ecommerce_deportivo`.`producto_caracteristicas` (`id_caract`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`direcciones_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`direcciones_usuario` (
  `id_direccion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `nombre_destinatario` VARCHAR(150) NULL DEFAULT NULL,
  `telefono_contacto` VARCHAR(20) NULL DEFAULT NULL,
  `calle` VARCHAR(150) NOT NULL,
  `numero_exterior` VARCHAR(20) NOT NULL,
  `numero_interior` VARCHAR(20) NULL DEFAULT NULL,
  `colonia` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `referencia` TEXT NULL DEFAULT NULL,
  `principal` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_direccion`),
  INDEX `FK_DIRECCION_USUARIO` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_DIRECCION_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecommerce_deportivo`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`pedidos` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_direccion` INT(11) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('pendiente', 'pagado', 'enviado', 'entregado', 'cancelado') NULL DEFAULT 'pendiente',
  `fecha_pedido` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_pedido`),
  INDEX `FK_PEDIDO_USUARIO` (`id_usuario` ASC) VISIBLE,
  INDEX `FK_PEDIDO_DIRECCION` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `FK_PEDIDO_DIRECCION`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `ecommerce_deportivo`.`direcciones_usuario` (`id_direccion`),
  CONSTRAINT `FK_PEDIDO_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecommerce_deportivo`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`pagos` (
  `id_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pedido` INT(11) NOT NULL,
  `metodo_pago` VARCHAR(50) NULL DEFAULT NULL,
  `estado_pago` VARCHAR(50) NULL DEFAULT NULL,
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_pago` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_pago`),
  INDEX `FK_PAGO_PEDIDO` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `FK_PAGO_PEDIDO`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `ecommerce_deportivo`.`pedidos` (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`pedido_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`pedido_detalle` (
  `id_detalle` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pedido` INT(11) NOT NULL,
  `id_caract` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `FK_DETALLE_PEDIDO` (`id_pedido` ASC) VISIBLE,
  INDEX `FK_DETALLE_P_CARACT` (`id_caract` ASC) VISIBLE,
  CONSTRAINT `FK_DETALLE_PEDIDO`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `ecommerce_deportivo`.`pedidos` (`id_pedido`),
  CONSTRAINT `FK_DETALLE_P_CARACT`
    FOREIGN KEY (`id_caract`)
    REFERENCES `ecommerce_deportivo`.`producto_caracteristicas` (`id_caract`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecommerce_deportivo`.`producto_imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_deportivo`.`producto_imagenes` (
  `id_imagen` INT(11) NOT NULL AUTO_INCREMENT,
  `id_caract` INT(11) NOT NULL,
  `url_imagen` VARCHAR(500) NOT NULL,
  `principal` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_imagen`),
  INDEX `FK_IMG_PRODUCTO` (`id_caract` ASC) VISIBLE,
  CONSTRAINT `FK_IMG_PRODUCTO`
    FOREIGN KEY (`id_caract`)
    REFERENCES `ecommerce_deportivo`.`producto_caracteristicas` (`id_caract`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
